/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CoreConceptsExecutionContextGuideRouteImport } from './routes/core-concepts/execution-context-guide'
import { Route as CoreConceptsExecutionContextScopeIndexRouteImport } from './routes/core-concepts/execution-context-scope/index'
import { Route as CoreConceptsExecutionContextScopeDay7RouteImport } from './routes/core-concepts/execution-context-scope/day-7'
import { Route as CoreConceptsExecutionContextScopeDay6RouteImport } from './routes/core-concepts/execution-context-scope/day-6'
import { Route as CoreConceptsExecutionContextScopeDay5RouteImport } from './routes/core-concepts/execution-context-scope/day-5'
import { Route as CoreConceptsExecutionContextScopeDay4RouteImport } from './routes/core-concepts/execution-context-scope/day-4'
import { Route as CoreConceptsExecutionContextScopeDay3RouteImport } from './routes/core-concepts/execution-context-scope/day-3'
import { Route as CoreConceptsExecutionContextScopeDay2RouteImport } from './routes/core-concepts/execution-context-scope/day-2'
import { Route as CoreConceptsExecutionContextScopeDay1RouteImport } from './routes/core-concepts/execution-context-scope/day-1'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CoreConceptsExecutionContextGuideRoute =
  CoreConceptsExecutionContextGuideRouteImport.update({
    id: '/core-concepts/execution-context-guide',
    path: '/core-concepts/execution-context-guide',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeIndexRoute =
  CoreConceptsExecutionContextScopeIndexRouteImport.update({
    id: '/core-concepts/execution-context-scope/',
    path: '/core-concepts/execution-context-scope/',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay7Route =
  CoreConceptsExecutionContextScopeDay7RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-7',
    path: '/core-concepts/execution-context-scope/day-7',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay6Route =
  CoreConceptsExecutionContextScopeDay6RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-6',
    path: '/core-concepts/execution-context-scope/day-6',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay5Route =
  CoreConceptsExecutionContextScopeDay5RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-5',
    path: '/core-concepts/execution-context-scope/day-5',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay4Route =
  CoreConceptsExecutionContextScopeDay4RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-4',
    path: '/core-concepts/execution-context-scope/day-4',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay3Route =
  CoreConceptsExecutionContextScopeDay3RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-3',
    path: '/core-concepts/execution-context-scope/day-3',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay2Route =
  CoreConceptsExecutionContextScopeDay2RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-2',
    path: '/core-concepts/execution-context-scope/day-2',
    getParentRoute: () => rootRouteImport,
  } as any)
const CoreConceptsExecutionContextScopeDay1Route =
  CoreConceptsExecutionContextScopeDay1RouteImport.update({
    id: '/core-concepts/execution-context-scope/day-1',
    path: '/core-concepts/execution-context-scope/day-1',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/core-concepts/execution-context-guide': typeof CoreConceptsExecutionContextGuideRoute
  '/core-concepts/execution-context-scope/day-1': typeof CoreConceptsExecutionContextScopeDay1Route
  '/core-concepts/execution-context-scope/day-2': typeof CoreConceptsExecutionContextScopeDay2Route
  '/core-concepts/execution-context-scope/day-3': typeof CoreConceptsExecutionContextScopeDay3Route
  '/core-concepts/execution-context-scope/day-4': typeof CoreConceptsExecutionContextScopeDay4Route
  '/core-concepts/execution-context-scope/day-5': typeof CoreConceptsExecutionContextScopeDay5Route
  '/core-concepts/execution-context-scope/day-6': typeof CoreConceptsExecutionContextScopeDay6Route
  '/core-concepts/execution-context-scope/day-7': typeof CoreConceptsExecutionContextScopeDay7Route
  '/core-concepts/execution-context-scope/': typeof CoreConceptsExecutionContextScopeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/core-concepts/execution-context-guide': typeof CoreConceptsExecutionContextGuideRoute
  '/core-concepts/execution-context-scope/day-1': typeof CoreConceptsExecutionContextScopeDay1Route
  '/core-concepts/execution-context-scope/day-2': typeof CoreConceptsExecutionContextScopeDay2Route
  '/core-concepts/execution-context-scope/day-3': typeof CoreConceptsExecutionContextScopeDay3Route
  '/core-concepts/execution-context-scope/day-4': typeof CoreConceptsExecutionContextScopeDay4Route
  '/core-concepts/execution-context-scope/day-5': typeof CoreConceptsExecutionContextScopeDay5Route
  '/core-concepts/execution-context-scope/day-6': typeof CoreConceptsExecutionContextScopeDay6Route
  '/core-concepts/execution-context-scope/day-7': typeof CoreConceptsExecutionContextScopeDay7Route
  '/core-concepts/execution-context-scope': typeof CoreConceptsExecutionContextScopeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/core-concepts/execution-context-guide': typeof CoreConceptsExecutionContextGuideRoute
  '/core-concepts/execution-context-scope/day-1': typeof CoreConceptsExecutionContextScopeDay1Route
  '/core-concepts/execution-context-scope/day-2': typeof CoreConceptsExecutionContextScopeDay2Route
  '/core-concepts/execution-context-scope/day-3': typeof CoreConceptsExecutionContextScopeDay3Route
  '/core-concepts/execution-context-scope/day-4': typeof CoreConceptsExecutionContextScopeDay4Route
  '/core-concepts/execution-context-scope/day-5': typeof CoreConceptsExecutionContextScopeDay5Route
  '/core-concepts/execution-context-scope/day-6': typeof CoreConceptsExecutionContextScopeDay6Route
  '/core-concepts/execution-context-scope/day-7': typeof CoreConceptsExecutionContextScopeDay7Route
  '/core-concepts/execution-context-scope/': typeof CoreConceptsExecutionContextScopeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/core-concepts/execution-context-guide'
    | '/core-concepts/execution-context-scope/day-1'
    | '/core-concepts/execution-context-scope/day-2'
    | '/core-concepts/execution-context-scope/day-3'
    | '/core-concepts/execution-context-scope/day-4'
    | '/core-concepts/execution-context-scope/day-5'
    | '/core-concepts/execution-context-scope/day-6'
    | '/core-concepts/execution-context-scope/day-7'
    | '/core-concepts/execution-context-scope/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/core-concepts/execution-context-guide'
    | '/core-concepts/execution-context-scope/day-1'
    | '/core-concepts/execution-context-scope/day-2'
    | '/core-concepts/execution-context-scope/day-3'
    | '/core-concepts/execution-context-scope/day-4'
    | '/core-concepts/execution-context-scope/day-5'
    | '/core-concepts/execution-context-scope/day-6'
    | '/core-concepts/execution-context-scope/day-7'
    | '/core-concepts/execution-context-scope'
  id:
    | '__root__'
    | '/'
    | '/core-concepts/execution-context-guide'
    | '/core-concepts/execution-context-scope/day-1'
    | '/core-concepts/execution-context-scope/day-2'
    | '/core-concepts/execution-context-scope/day-3'
    | '/core-concepts/execution-context-scope/day-4'
    | '/core-concepts/execution-context-scope/day-5'
    | '/core-concepts/execution-context-scope/day-6'
    | '/core-concepts/execution-context-scope/day-7'
    | '/core-concepts/execution-context-scope/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CoreConceptsExecutionContextGuideRoute: typeof CoreConceptsExecutionContextGuideRoute
  CoreConceptsExecutionContextScopeDay1Route: typeof CoreConceptsExecutionContextScopeDay1Route
  CoreConceptsExecutionContextScopeDay2Route: typeof CoreConceptsExecutionContextScopeDay2Route
  CoreConceptsExecutionContextScopeDay3Route: typeof CoreConceptsExecutionContextScopeDay3Route
  CoreConceptsExecutionContextScopeDay4Route: typeof CoreConceptsExecutionContextScopeDay4Route
  CoreConceptsExecutionContextScopeDay5Route: typeof CoreConceptsExecutionContextScopeDay5Route
  CoreConceptsExecutionContextScopeDay6Route: typeof CoreConceptsExecutionContextScopeDay6Route
  CoreConceptsExecutionContextScopeDay7Route: typeof CoreConceptsExecutionContextScopeDay7Route
  CoreConceptsExecutionContextScopeIndexRoute: typeof CoreConceptsExecutionContextScopeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-guide': {
      id: '/core-concepts/execution-context-guide'
      path: '/core-concepts/execution-context-guide'
      fullPath: '/core-concepts/execution-context-guide'
      preLoaderRoute: typeof CoreConceptsExecutionContextGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/': {
      id: '/core-concepts/execution-context-scope/'
      path: '/core-concepts/execution-context-scope'
      fullPath: '/core-concepts/execution-context-scope/'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-7': {
      id: '/core-concepts/execution-context-scope/day-7'
      path: '/core-concepts/execution-context-scope/day-7'
      fullPath: '/core-concepts/execution-context-scope/day-7'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-6': {
      id: '/core-concepts/execution-context-scope/day-6'
      path: '/core-concepts/execution-context-scope/day-6'
      fullPath: '/core-concepts/execution-context-scope/day-6'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-5': {
      id: '/core-concepts/execution-context-scope/day-5'
      path: '/core-concepts/execution-context-scope/day-5'
      fullPath: '/core-concepts/execution-context-scope/day-5'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-4': {
      id: '/core-concepts/execution-context-scope/day-4'
      path: '/core-concepts/execution-context-scope/day-4'
      fullPath: '/core-concepts/execution-context-scope/day-4'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-3': {
      id: '/core-concepts/execution-context-scope/day-3'
      path: '/core-concepts/execution-context-scope/day-3'
      fullPath: '/core-concepts/execution-context-scope/day-3'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-2': {
      id: '/core-concepts/execution-context-scope/day-2'
      path: '/core-concepts/execution-context-scope/day-2'
      fullPath: '/core-concepts/execution-context-scope/day-2'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/core-concepts/execution-context-scope/day-1': {
      id: '/core-concepts/execution-context-scope/day-1'
      path: '/core-concepts/execution-context-scope/day-1'
      fullPath: '/core-concepts/execution-context-scope/day-1'
      preLoaderRoute: typeof CoreConceptsExecutionContextScopeDay1RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CoreConceptsExecutionContextGuideRoute:
    CoreConceptsExecutionContextGuideRoute,
  CoreConceptsExecutionContextScopeDay1Route:
    CoreConceptsExecutionContextScopeDay1Route,
  CoreConceptsExecutionContextScopeDay2Route:
    CoreConceptsExecutionContextScopeDay2Route,
  CoreConceptsExecutionContextScopeDay3Route:
    CoreConceptsExecutionContextScopeDay3Route,
  CoreConceptsExecutionContextScopeDay4Route:
    CoreConceptsExecutionContextScopeDay4Route,
  CoreConceptsExecutionContextScopeDay5Route:
    CoreConceptsExecutionContextScopeDay5Route,
  CoreConceptsExecutionContextScopeDay6Route:
    CoreConceptsExecutionContextScopeDay6Route,
  CoreConceptsExecutionContextScopeDay7Route:
    CoreConceptsExecutionContextScopeDay7Route,
  CoreConceptsExecutionContextScopeIndexRoute:
    CoreConceptsExecutionContextScopeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
